//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Discounts = new HashSet<Discount>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> PublishingHouseID { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<System.DateTime> DateofPublishing { get; set; }
        public Nullable<decimal> PrimeCost { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<bool> IsSequel { get; set; }
        public string Status { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual PublishingHouses PublishingHous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
